print("Welcome to the chatbox")

name = input("First of all, who are you?")
print("wow, what a nice name, " + name + ".\n")

life = input("how's life")
print(life + "?" + "yeah me too" + ".\n")
print("." + "\n")
print("." + "\n")
print("." + "\n")
print("." + "\n")
print("." + "\n")
nothing = input("there's nothing to talk about huh")
print("yeah ok moving on" + "\n")
weather = input("so how's the weather?")
print("cool, very interesting" + "\n")
talk = input("ok, then what do you want to talk about?")
print(talk + "?" + "that doesn't sound very interesting" + ".\n")
print("wow what a nice conversation, this was definitely fulfilling")